### ISSUE TITLE
Firefox: grayscale-fade on img incorrectly sizes colored image

### ISSUE THREAD

**Issue by binyamindavid** [karlhorky/gray#14]
``` css
<img> tag with transition  
```

The image zooms on firefox on hover.  Image is zoomed about 300%.

``` css
.grayscale {
  /* Firefox 10+, Firefox on Android */
  filter: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'><filter id='grayscale'><feColorMatrix type='matrix' values='0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0'/></filter></svg>#grayscale");
  /* IE 6-9 */
  filter: gray;
  /*
    Chrome 19+,
    Safari 6+,
    Safari 6+ iOS,
    Opera 15+
  */
  -webkit-filter: grayscale(100%);
  &.grayscale-fade {
    @include vendor(transition, -webkit-filter .5s, webkit);
    &:hover {
      -webkit-filter: grayscale(0%);
      filter: none;
    }
  }
}

.grayscale-replaced.grayscale-fade {
  svg {
    opacity: 1;
    @include vendor(transition, opacity .5s ease, webkit moz official);
  }
  &:hover svg {
    opacity: 0;
  }
}
```

![hover](https://cloud.githubusercontent.com/assets/972227/3791445/862ef918-1b3d-11e4-95aa-dd4464f6187c.jpg)
