### ISSUE TITLE
Toggle greyscale doesn't work

### ISSUE THREAD

**Issue by JulianMBr** [karlhorky/gray#19]
Hey,

I'm currently working on a simple toggle function for this. But it seems they removing/adding the class is not working (IE11).
However if I  have .grayscale as standard class attribute it works (without the toggle obv.).

I'm quite new to javascript/jquery but the only thing I could think of is that while the first page render the code will be replaced with the SVG part, however - removing the grayscale class wont work.

Any idea?

**Comment by JulianMBr** [comment]
Still didnt got it working. Any idea?

**Comment by karlhorky** [comment]
Removing the class again in polyfill browsers doesn't work at the moment.

As a workaround for now, you can:
- include the `grayscale-fade` class 
- add a new class (`color` in the example below) to toggle the opacity of the `svg` element
- remove the `:hover` rules with the transitions [here](https://github.com/karlhorky/gray/blob/gh-pages/css/gray.css#L18) and [here](https://github.com/karlhorky/gray/blob/gh-pages/css/gray.css#L28-29)

``` css
.grayscale-fade.color {
  -webkit-filter: grayscale(0%);
  filter: none;
}

.grayscale-replaced.grayscale-fade.color svg {
  opacity: 0;
}
```
