### ISSUE TITLE
Hover effect inverted

### ISSUE THREAD

**Issue by wazZzif** [karlhorky/gray#6]
I would like to have images stay as colored on load and turn gray only on hover, and back to color on mouseleave. Specifically for ie10.

Would be great to have this feature be part of this awesome plugin.

**Comment by karlhorky** [comment]
For fading to gray instead of to color, you would just need to change the CSS from `gray.css`. You would first set the filter to none on the `.grayscale-fade` class directly and then add the filter back on hover:

``` css
.grayscale.grayscale-fade {
  -webkit-filter: grayscale(0);
  filter:         grayscale(0);
  filter:         none;
}

.grayscale.grayscale-fade:hover {
  filter: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'><filter id='grayscale'><feColorMatrix type='matrix' values='0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0'/></filter></svg>#grayscale");
  -webkit-filter: grayscale(1);
  filter:         grayscale(1);
  filter:         gray;
}
```

Likewise for IE10 and other browsers that use the polyfill - you would first set `opacity` to 0 on the grayscale svg directly and then change it to 1 on hover:

``` css
.grayscale-replaced.grayscale-fade svg {
  opacity: 0;
  -webkit-transition: opacity .5s ease;
  transition: opacity .5s ease;
}

.grayscale-replaced.grayscale-fade:hover svg {
  opacity: 1;
}
```
